language: android

sudo: required

jdk:
- oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install latest Android SDK tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository # Design Support library
    - sys-img-armeabi-v7a-android-21 # system image (emulator)
  licenses:
  - android-sdk-license-.+
  
env:
  global:
  - ADB_INSTALL_TIMEOUT=8 # timeout (in minutes)

before_script:
  # Automatically accept all SDK licences
  - echo yes | android update sdk --no-ui --all --filter build-tools-24.0.2,android-24,extra-android-m2repository
  # Emulator Management: create, start & wait
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew build connectedCheck
  - ./gradlew connectedAndroidTest
